# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.cache/wt [current_project]
set_property parent.project_path C:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.srcs/sources_1/ip/ila_0/ila_0.dcp
set_property used_in_implementation false [get_files c:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.srcs/sources_1/ip/ila_0/ila_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.srcs/sources_1/new/sine_gen.v
  C:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.srcs/sources_1/new/pwm_gen.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files C:/Users/argo7/Desktop/project_Sine_PWM/project_Sine_PWM.srcs/constrs_1/new/constr.xdc]


synth_design -top pwm_gen -part xc7z020clg484-1


write_checkpoint -force -noxdef pwm_gen.dcp

catch { report_utilization -file pwm_gen_utilization_synth.rpt -pb pwm_gen_utilization_synth.pb }
